// <auto-generated />
using System;
using HospitalBomCodigo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalBomCodigo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311005906_adicionando-paciente")]
    partial class adicionandopaciente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("HospitalBomCodigo.Models.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResultReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3629c62b-56da-4185-a3f6-0d4d0cd47aa9"),
                            Description = "Sapiente reprehenderit doloremque eligendi beatae laborum vel illum sed eius.",
                            NotificationSent = false,
                            PatientId = new Guid("801c893a-a993-4713-b614-c375a5194d6a"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("75cb9219-4a5e-4786-a3c4-7e217f1ab016"),
                            Description = "Perspiciatis molestiae sit optio.",
                            NotificationSent = false,
                            PatientId = new Guid("be639332-05e1-4012-a914-287e32c63fdb"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("c5b2110c-6c4a-4cc6-a739-ed40c7245da4"),
                            Description = "Reiciendis enim qui et.",
                            NotificationSent = false,
                            PatientId = new Guid("cc61a2c7-7279-4740-b299-7be69d293a14"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("096dd0b3-5682-43f9-9fdc-009126afa838"),
                            Description = "In sit non id nulla temporibus aperiam laboriosam et qui.",
                            NotificationSent = false,
                            PatientId = new Guid("e917ad6d-0d06-4e79-87aa-3311c47f5513"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("d7c57fa1-a6d2-4643-b57c-81b3ef825bf5"),
                            Description = "Maxime aliquid maiores quis voluptas unde.",
                            NotificationSent = false,
                            PatientId = new Guid("e2d10d34-682c-4b9e-8654-2cede9223c6e"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("c84c3b8a-8469-4e49-9774-029acb96b092"),
                            Description = "Omnis ab rerum alias excepturi eos doloribus quisquam assumenda.",
                            NotificationSent = false,
                            PatientId = new Guid("74bbd5e5-863c-4fc7-ad84-a965a4235be6"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("660b7aea-322b-498d-9663-c1b0e82bd556"),
                            Description = "A sint quos laboriosam tempore repellendus.",
                            NotificationSent = false,
                            PatientId = new Guid("8673a8b0-ee19-4a8a-8cd1-c5c938a7121e"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("b69928ac-cd79-47c3-b2cd-bb10df62a480"),
                            Description = "Consequatur labore accusantium voluptatum voluptatem.",
                            NotificationSent = false,
                            PatientId = new Guid("801c893a-a993-4713-b614-c375a5194d6a"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("776777ed-4f94-45ae-8cbc-6a5a0e567744"),
                            Description = "Laboriosam sit recusandae sit iure accusantium consequatur voluptatem pariatur deleniti.",
                            NotificationSent = false,
                            PatientId = new Guid("314c9c50-143f-40d8-99aa-fc215c75020e"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("94453c9c-f891-47ff-b9c6-a938c40fdd2f"),
                            Description = "Quibusdam dolorum possimus tenetur voluptate temporibus repudiandae excepturi.",
                            NotificationSent = false,
                            PatientId = new Guid("077bedb9-7ba6-4475-a786-241a1833b98e"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("18b403a3-196c-4e26-b428-39283f7ac78e"),
                            Description = "Est nesciunt voluptas enim consequatur in voluptate soluta dolores optio.",
                            NotificationSent = false,
                            PatientId = new Guid("2d56b175-31e6-4795-9768-8acf3c1fbb02"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("9b218dc7-dae1-4a85-aa17-4d7ec2f636d8"),
                            Description = "Eum minus eum et veniam.",
                            NotificationSent = false,
                            PatientId = new Guid("314c9c50-143f-40d8-99aa-fc215c75020e"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("88dafbca-a25a-4d13-8f25-36037ab06133"),
                            Description = "Aperiam architecto culpa non et delectus labore quis.",
                            NotificationSent = false,
                            PatientId = new Guid("610ffa71-cc55-43e6-9045-3bf55f3fd998"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("46e5d01e-ba30-4f1f-ba38-3715109cc099"),
                            Description = "Sequi et accusantium suscipit molestiae consequatur sint.",
                            NotificationSent = false,
                            PatientId = new Guid("5f9b6377-d168-46d3-bc95-78429b9da3c3"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("3d228dec-a82a-4ab8-bc3e-b6f7c30ad7ab"),
                            Description = "Quia eveniet et consectetur quisquam eveniet eligendi tenetur in est.",
                            NotificationSent = false,
                            PatientId = new Guid("2d56b175-31e6-4795-9768-8acf3c1fbb02"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("facf2e95-ed5d-45ae-9fed-60023f57afe9"),
                            Description = "Ipsam dolorem et iusto.",
                            NotificationSent = false,
                            PatientId = new Guid("c43d3329-fffd-4f1f-a068-c3423058f5e8"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("e4693721-b51a-4d7c-8489-9f5657bc1a40"),
                            Description = "Laboriosam illum aliquid dolores omnis voluptas voluptas voluptatem accusamus aliquid.",
                            NotificationSent = false,
                            PatientId = new Guid("c43d3329-fffd-4f1f-a068-c3423058f5e8"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("05c1c9c0-5654-4a61-a924-9ce871d3181f"),
                            Description = "Earum quo officiis soluta dicta aperiam vel reprehenderit dolorem.",
                            NotificationSent = false,
                            PatientId = new Guid("077bedb9-7ba6-4475-a786-241a1833b98e"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("12ad1eb9-9c20-4798-800b-39a29de8d0fe"),
                            Description = "Error dolorum omnis dignissimos vel ut.",
                            NotificationSent = false,
                            PatientId = new Guid("82996906-b503-4d5c-b68b-be5d53521195"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("a46d66ff-71c3-410c-b711-6939c0ef2aa2"),
                            Description = "Illum at vero explicabo.",
                            NotificationSent = false,
                            PatientId = new Guid("7cda5c1f-3e6f-442c-a67d-425c12c41129"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("0343a4a1-604a-4ffe-82cd-0bd5935c260f"),
                            Description = "Dolore exercitationem et eveniet non quis commodi.",
                            NotificationSent = false,
                            PatientId = new Guid("f256cabc-721b-43f5-ae44-be20e235da69"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("2e2df93e-9c85-4a66-a52d-58f2f0387632"),
                            Description = "Libero dolore quibusdam libero aut sit.",
                            NotificationSent = false,
                            PatientId = new Guid("2f2b366e-4c70-4233-b6ba-970e5b7bca18"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("261352ee-d35a-48ba-9ec7-bb67784231fe"),
                            Description = "Qui ratione eum vel sed ut.",
                            NotificationSent = false,
                            PatientId = new Guid("cc61a2c7-7279-4740-b299-7be69d293a14"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("6f170993-38bd-470e-a38e-59dff320de0a"),
                            Description = "Commodi voluptates magni sunt quasi laboriosam vitae.",
                            NotificationSent = false,
                            PatientId = new Guid("584609b7-a06e-49bc-bade-f943854bee0a"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("5aa553a6-a441-4306-ade7-fefa189e56ff"),
                            Description = "Aut suscipit fugit.",
                            NotificationSent = false,
                            PatientId = new Guid("2d56b175-31e6-4795-9768-8acf3c1fbb02"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("5d41589e-b537-42c8-a5d6-676c811f6555"),
                            Description = "Architecto officia sequi qui repellendus vel nam dolor culpa quod.",
                            NotificationSent = false,
                            PatientId = new Guid("cc61a2c7-7279-4740-b299-7be69d293a14"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("8ae9c032-3e91-4439-9d1d-307cecdedb72"),
                            Description = "Consequatur delectus consequatur a.",
                            NotificationSent = false,
                            PatientId = new Guid("a5281a12-090d-46a9-973b-f8cf76327393"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("f206c79f-d8d7-4586-8526-d6c932ecfdf0"),
                            Description = "Tempore magnam harum natus ut velit nam ad.",
                            NotificationSent = false,
                            PatientId = new Guid("2d56b175-31e6-4795-9768-8acf3c1fbb02"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("8c72e8e0-515d-4451-a632-1d6927f30df2"),
                            Description = "Tempore unde voluptatibus accusamus hic autem.",
                            NotificationSent = false,
                            PatientId = new Guid("169067fd-f917-4628-8b4c-ecba7edb1e47"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("761bd2d5-4680-49e8-9d8b-59e187a98888"),
                            Description = "Facilis eveniet dignissimos ad.",
                            NotificationSent = false,
                            PatientId = new Guid("9c7c2fe7-b8a5-4e6d-b09b-29db43d2c482"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("6605b209-a775-4501-8be9-58782436ac21"),
                            Description = "Voluptatem laboriosam necessitatibus eveniet in.",
                            NotificationSent = false,
                            PatientId = new Guid("c43d3329-fffd-4f1f-a068-c3423058f5e8"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("333018cb-86ba-4a82-9508-9d0c2e0b0b38"),
                            Description = "Quia quas corrupti labore nesciunt officiis nesciunt ipsam necessitatibus.",
                            NotificationSent = false,
                            PatientId = new Guid("e917ad6d-0d06-4e79-87aa-3311c47f5513"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("cd588b19-dbf0-4486-818a-1e5fb7ace7df"),
                            Description = "In esse et.",
                            NotificationSent = false,
                            PatientId = new Guid("584609b7-a06e-49bc-bade-f943854bee0a"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("c9d832ab-004d-4f12-9488-943d25240099"),
                            Description = "Voluptas debitis eos libero fuga saepe quas sunt beatae.",
                            NotificationSent = false,
                            PatientId = new Guid("9c7c2fe7-b8a5-4e6d-b09b-29db43d2c482"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("bcf2c9ea-4e24-41a7-b4bd-65caceb80348"),
                            Description = "Delectus eum et beatae a beatae.",
                            NotificationSent = false,
                            PatientId = new Guid("584609b7-a06e-49bc-bade-f943854bee0a"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("a63fa6cf-59ad-401e-94f8-adf5b7593a27"),
                            Description = "Aut id in nihil dolorum saepe.",
                            NotificationSent = false,
                            PatientId = new Guid("2f2b366e-4c70-4233-b6ba-970e5b7bca18"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("3a9f16ac-2e0f-4589-957e-f9624f3aca90"),
                            Description = "Ad asperiores aut harum.",
                            NotificationSent = false,
                            PatientId = new Guid("7cda5c1f-3e6f-442c-a67d-425c12c41129"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("16aab0c0-dcde-4607-a095-ed2213487b22"),
                            Description = "Qui eos qui veritatis doloremque magni nisi molestiae.",
                            NotificationSent = false,
                            PatientId = new Guid("e2d10d34-682c-4b9e-8654-2cede9223c6e"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("955c17cf-4245-4417-b6eb-11e4ee01b1ae"),
                            Description = "Laboriosam sapiente amet et repellat ut.",
                            NotificationSent = false,
                            PatientId = new Guid("1dcaee80-b7b2-401e-8104-e77326d8a184"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("bdf86ab1-7bf9-4508-9c95-84a28448f631"),
                            Description = "Molestiae odio consequatur omnis deserunt quisquam quas sint.",
                            NotificationSent = false,
                            PatientId = new Guid("f46eb19f-563c-4dca-bf2a-0701338f35b1"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("a1005ca8-cec7-47cf-988f-0659681aee6a"),
                            Description = "Debitis eaque dolore delectus cumque et velit est.",
                            NotificationSent = false,
                            PatientId = new Guid("fabfea9c-2351-4ce1-aa86-51e7d9a6628f"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("f58ad9f3-e8c5-4f52-abd4-cc1d28fff834"),
                            Description = "Dolorem autem qui est necessitatibus exercitationem consequatur nihil pariatur.",
                            NotificationSent = false,
                            PatientId = new Guid("9c7c2fe7-b8a5-4e6d-b09b-29db43d2c482"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("a5c1a843-d0f5-4943-93e4-d9f89c68fa83"),
                            Description = "Et cupiditate voluptate sit voluptatem vitae voluptas aut.",
                            NotificationSent = false,
                            PatientId = new Guid("cc968289-098b-4909-8d09-c7538bd44509"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("f397bfa8-faaa-4709-8a21-aafa9672c613"),
                            Description = "Modi ut rerum et eligendi molestiae.",
                            NotificationSent = false,
                            PatientId = new Guid("4ac9436d-74a2-41f1-86bb-2d268ff56449"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("41096d45-1d16-4561-b597-b8568b5d72b3"),
                            Description = "Quaerat harum adipisci minima et.",
                            NotificationSent = false,
                            PatientId = new Guid("7cda5c1f-3e6f-442c-a67d-425c12c41129"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("55f7e9fd-c10b-420b-b3af-3180b537cc18"),
                            Description = "Maiores voluptatibus voluptatem expedita vel.",
                            NotificationSent = false,
                            PatientId = new Guid("f256cabc-721b-43f5-ae44-be20e235da69"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("8d60583c-94f1-4323-b2e2-e9f995024e61"),
                            Description = "Officiis vitae rerum cupiditate maxime qui consequatur rerum sint.",
                            NotificationSent = false,
                            PatientId = new Guid("d262d5a0-7b09-419e-98a1-c21d57c52cf1"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("b9551be6-9f46-48f9-b1fb-be77b7e4f61a"),
                            Description = "Magni est harum in excepturi officiis et.",
                            NotificationSent = false,
                            PatientId = new Guid("d262d5a0-7b09-419e-98a1-c21d57c52cf1"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("534b3e32-a83b-4be3-814f-43d8219bc81f"),
                            Description = "Eligendi voluptatum porro.",
                            NotificationSent = false,
                            PatientId = new Guid("077bedb9-7ba6-4475-a786-241a1833b98e"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("da3ba8f6-ecdf-40c3-84c8-43305cb43fc8"),
                            Description = "Labore non velit.",
                            NotificationSent = false,
                            PatientId = new Guid("2f2b366e-4c70-4233-b6ba-970e5b7bca18"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("d6f2aff4-8e30-4f9f-b7f4-51f69024976b"),
                            Description = "Qui consectetur ut voluptatem voluptatibus.",
                            NotificationSent = false,
                            PatientId = new Guid("f256cabc-721b-43f5-ae44-be20e235da69"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("de4c074c-1b11-4d4d-a969-7f794abfa2cc"),
                            Description = "Magni excepturi ipsam.",
                            NotificationSent = false,
                            PatientId = new Guid("d262d5a0-7b09-419e-98a1-c21d57c52cf1"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("ff18b5ee-854b-4dab-ba2e-9c83d997ca77"),
                            Description = "Soluta beatae molestiae animi nobis recusandae ut.",
                            NotificationSent = false,
                            PatientId = new Guid("584609b7-a06e-49bc-bade-f943854bee0a"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("154c8afc-7c77-4e24-8009-5a59ea057319"),
                            Description = "Totam voluptatem in dicta non minima facere.",
                            NotificationSent = false,
                            PatientId = new Guid("1dcaee80-b7b2-401e-8104-e77326d8a184"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("5e19f141-62b6-44df-b761-db113ba2d2ef"),
                            Description = "Voluptate praesentium dolor autem.",
                            NotificationSent = false,
                            PatientId = new Guid("d974c7c0-5fb1-47e1-8b98-e4aed47a4609"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("b791621f-b525-4a31-ae44-afedcd764783"),
                            Description = "Fuga in nisi ad.",
                            NotificationSent = false,
                            PatientId = new Guid("314c9c50-143f-40d8-99aa-fc215c75020e"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("05f3fb78-2e5a-4af6-a25e-e05b18fd22ef"),
                            Description = "Totam qui dolore.",
                            NotificationSent = false,
                            PatientId = new Guid("801c893a-a993-4713-b614-c375a5194d6a"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("fefaf762-4d4c-4f1e-9397-ea0634068611"),
                            Description = "Saepe qui at possimus quia.",
                            NotificationSent = false,
                            PatientId = new Guid("4762ffbb-2c58-47ad-bc41-965921c86612"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("0fda9eb6-8796-41f3-aa0b-03b87eb279a5"),
                            Description = "Totam voluptatem alias at.",
                            NotificationSent = false,
                            PatientId = new Guid("314c9c50-143f-40d8-99aa-fc215c75020e"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("583dfc7c-d54c-4fa7-985a-36ac54e34bee"),
                            Description = "Reiciendis et placeat est optio aut.",
                            NotificationSent = false,
                            PatientId = new Guid("077bedb9-7ba6-4475-a786-241a1833b98e"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("7592e1e1-dc0b-4bad-ae1d-502c66ca1c30"),
                            Description = "Ipsam facere sunt.",
                            NotificationSent = false,
                            PatientId = new Guid("a5281a12-090d-46a9-973b-f8cf76327393"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("e2cf099c-5013-49f1-9ca8-00c6aea297a5"),
                            Description = "Tenetur deleniti accusamus ipsum qui.",
                            NotificationSent = false,
                            PatientId = new Guid("610ffa71-cc55-43e6-9045-3bf55f3fd998"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("10661dd8-f06a-4137-8859-9ad587cc2210"),
                            Description = "Magnam quod est ut omnis ut.",
                            NotificationSent = false,
                            PatientId = new Guid("9c7c2fe7-b8a5-4e6d-b09b-29db43d2c482"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("161beb25-baf1-457a-a072-666e6196ab63"),
                            Description = "Accusamus mollitia libero adipisci optio consequuntur ex rerum.",
                            NotificationSent = false,
                            PatientId = new Guid("7cda5c1f-3e6f-442c-a67d-425c12c41129"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("f067e5d1-a14a-4f0a-9d57-c6eba958a98f"),
                            Description = "Vel sequi tenetur dolorum eos esse.",
                            NotificationSent = false,
                            PatientId = new Guid("e917ad6d-0d06-4e79-87aa-3311c47f5513"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("7dce2a8f-7be0-44bc-9c2c-bb26a6f678c0"),
                            Description = "At voluptatem inventore.",
                            NotificationSent = false,
                            PatientId = new Guid("077bedb9-7ba6-4475-a786-241a1833b98e"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("1a07049f-ba73-408f-b995-b803e9d7fe55"),
                            Description = "Aliquam veniam aut tempore id dignissimos omnis temporibus tempore quaerat.",
                            NotificationSent = false,
                            PatientId = new Guid("74bbd5e5-863c-4fc7-ad84-a965a4235be6"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("01f99388-be14-4a54-b4ea-d9840bab1093"),
                            Description = "Commodi dolorem temporibus.",
                            NotificationSent = false,
                            PatientId = new Guid("314c9c50-143f-40d8-99aa-fc215c75020e"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("01e5d8c1-c7dc-4821-8d44-8333e0f5ead5"),
                            Description = "Non eveniet consequuntur ea magni consequatur id.",
                            NotificationSent = false,
                            PatientId = new Guid("a5281a12-090d-46a9-973b-f8cf76327393"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("e64a273f-4739-4110-8ffd-d01e19d8c471"),
                            Description = "Est et sed explicabo ipsam ducimus voluptate ea.",
                            NotificationSent = false,
                            PatientId = new Guid("d974c7c0-5fb1-47e1-8b98-e4aed47a4609"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("e2c1de8e-cf11-4b40-934b-5872a0c50f16"),
                            Description = "Qui dolorum quam nostrum.",
                            NotificationSent = false,
                            PatientId = new Guid("2f2b366e-4c70-4233-b6ba-970e5b7bca18"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("72973184-0d4c-4e7d-9cc3-fed36c2a3029"),
                            Description = "Ut consequatur natus minima quos alias.",
                            NotificationSent = false,
                            PatientId = new Guid("169067fd-f917-4628-8b4c-ecba7edb1e47"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("9472bd00-a8b4-4e50-8e92-27010812c1b4"),
                            Description = "Quo et illo.",
                            NotificationSent = false,
                            PatientId = new Guid("077bedb9-7ba6-4475-a786-241a1833b98e"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("b8ba2d8e-e692-4331-94ba-0f63cd3b4346"),
                            Description = "Et aut illo ut dolor et.",
                            NotificationSent = false,
                            PatientId = new Guid("d262d5a0-7b09-419e-98a1-c21d57c52cf1"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("9b5d9644-284b-4d62-b613-e2456d61540a"),
                            Description = "Provident vel vel vel ad voluptatem repellendus sed corrupti adipisci.",
                            NotificationSent = false,
                            PatientId = new Guid("077bedb9-7ba6-4475-a786-241a1833b98e"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("dc6a6bd8-d22c-465e-ad32-b74c7e1232b6"),
                            Description = "Et dolore autem reiciendis libero modi vero quasi quidem laudantium.",
                            NotificationSent = false,
                            PatientId = new Guid("5f9b6377-d168-46d3-bc95-78429b9da3c3"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("4e1bc593-771f-4525-a099-115e445a5bfe"),
                            Description = "Nulla debitis doloribus rem consequatur et ducimus similique.",
                            NotificationSent = false,
                            PatientId = new Guid("e2d10d34-682c-4b9e-8654-2cede9223c6e"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("42e4b848-2bef-47df-ae77-2c64e44898c4"),
                            Description = "Deserunt quo sit est.",
                            NotificationSent = false,
                            PatientId = new Guid("82996906-b503-4d5c-b68b-be5d53521195"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("48c2b5b1-4f94-4018-bd14-e5e95003638b"),
                            Description = "Quas ducimus molestias reprehenderit.",
                            NotificationSent = false,
                            PatientId = new Guid("f256cabc-721b-43f5-ae44-be20e235da69"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("bd6a217e-fea3-4a61-af7d-72a13fff09a0"),
                            Description = "Vel sit nobis iusto ratione.",
                            NotificationSent = false,
                            PatientId = new Guid("be639332-05e1-4012-a914-287e32c63fdb"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("7850de6e-0471-437e-af5d-b323e5194941"),
                            Description = "Facilis nulla totam.",
                            NotificationSent = false,
                            PatientId = new Guid("2f2b366e-4c70-4233-b6ba-970e5b7bca18"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("afb84b2f-4634-4dec-bf84-3332aec0d445"),
                            Description = "Sed quo officia earum.",
                            NotificationSent = false,
                            PatientId = new Guid("169067fd-f917-4628-8b4c-ecba7edb1e47"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("6405d131-e377-43f9-83c6-50d95e0c3653"),
                            Description = "Nemo quis ratione et molestiae.",
                            NotificationSent = false,
                            PatientId = new Guid("169067fd-f917-4628-8b4c-ecba7edb1e47"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("2c38147b-aac6-40cc-85a5-3e4e9ed7b75b"),
                            Description = "At repellat ratione dolores tempore quod veritatis.",
                            NotificationSent = false,
                            PatientId = new Guid("f256cabc-721b-43f5-ae44-be20e235da69"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("d5c5d62a-f516-4c91-8808-9e1793ad838d"),
                            Description = "Doloribus et quidem repellendus.",
                            NotificationSent = false,
                            PatientId = new Guid("077bedb9-7ba6-4475-a786-241a1833b98e"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("c30659c4-b698-4b4f-a72b-0a93365550f9"),
                            Description = "Assumenda veritatis pariatur doloremque necessitatibus at est sit.",
                            NotificationSent = false,
                            PatientId = new Guid("e2d10d34-682c-4b9e-8654-2cede9223c6e"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("d7eda034-d24a-4279-9d08-24ac16b75c87"),
                            Description = "Voluptate iste esse velit et nesciunt quae sequi animi ipsam.",
                            NotificationSent = false,
                            PatientId = new Guid("169067fd-f917-4628-8b4c-ecba7edb1e47"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("272e5f5b-8a17-4950-868b-94bf3a873130"),
                            Description = "Consectetur eos ut saepe minima.",
                            NotificationSent = false,
                            PatientId = new Guid("82996906-b503-4d5c-b68b-be5d53521195"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("0abb653b-2508-4acd-b3d2-e3d52485a80b"),
                            Description = "Aut consequatur sit qui modi nihil dolorem cum.",
                            NotificationSent = false,
                            PatientId = new Guid("e917ad6d-0d06-4e79-87aa-3311c47f5513"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("e539df81-5f2b-4e8f-9c4f-ba8d9add61cf"),
                            Description = "Eaque sint sit ea.",
                            NotificationSent = false,
                            PatientId = new Guid("5f9b6377-d168-46d3-bc95-78429b9da3c3"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("4483da76-ac25-4498-be00-a213d5cc8b20"),
                            Description = "Excepturi eveniet qui sit magnam ea in fuga neque.",
                            NotificationSent = false,
                            PatientId = new Guid("584609b7-a06e-49bc-bade-f943854bee0a"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("cf02107d-9690-4d3f-983f-125788624eb5"),
                            Description = "Molestias voluptatum necessitatibus ducimus tempore veniam.",
                            NotificationSent = false,
                            PatientId = new Guid("d974c7c0-5fb1-47e1-8b98-e4aed47a4609"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("f48af5a5-9215-44ba-8659-daa3855f15b6"),
                            Description = "Adipisci non dolor temporibus minima.",
                            NotificationSent = false,
                            PatientId = new Guid("077bedb9-7ba6-4475-a786-241a1833b98e"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("aae92902-0c6f-4055-a34e-81c75ac8e44d"),
                            Description = "Ut sint quam adipisci nihil ut.",
                            NotificationSent = false,
                            PatientId = new Guid("e917ad6d-0d06-4e79-87aa-3311c47f5513"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("a644d8d9-e147-4cd7-bdfa-ef1fd4c860fc"),
                            Description = "Fugiat qui velit sed expedita.",
                            NotificationSent = false,
                            PatientId = new Guid("d262d5a0-7b09-419e-98a1-c21d57c52cf1"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("a120191d-2c32-4b04-8b18-9922e0ea81cc"),
                            Description = "Suscipit eum aut est.",
                            NotificationSent = false,
                            PatientId = new Guid("be639332-05e1-4012-a914-287e32c63fdb"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("811d2001-0566-4b16-83ed-725f8236edf6"),
                            Description = "Consequatur et voluptates maiores rerum consectetur est.",
                            NotificationSent = false,
                            PatientId = new Guid("e917ad6d-0d06-4e79-87aa-3311c47f5513"),
                            Status = 1,
                            Type = "Raio-X"
                        },
                        new
                        {
                            Id = new Guid("1c04d903-1063-4f71-b241-e1f4745de3d2"),
                            Description = "Eligendi dolores doloribus autem qui voluptates omnis.",
                            NotificationSent = false,
                            PatientId = new Guid("f256cabc-721b-43f5-ae44-be20e235da69"),
                            Status = 1,
                            Type = "MRI"
                        },
                        new
                        {
                            Id = new Guid("c90add47-8b00-489d-bab0-5e6e7a904b16"),
                            Description = "Quas dolores sapiente.",
                            NotificationSent = false,
                            PatientId = new Guid("314c9c50-143f-40d8-99aa-fc215c75020e"),
                            Status = 1,
                            Type = "Exame de Sangue"
                        },
                        new
                        {
                            Id = new Guid("ca03d623-b9b1-4fbd-bd53-5ac22e84cb57"),
                            Description = "Voluptatem qui ea impedit quo earum.",
                            NotificationSent = false,
                            PatientId = new Guid("314c9c50-143f-40d8-99aa-fc215c75020e"),
                            Status = 1,
                            Type = "Raio-X"
                        });
                });

            modelBuilder.Entity("HospitalBomCodigo.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f9b6377-d168-46d3-bc95-78429b9da3c3"),
                            Document = "654.127.920-07",
                            LastName = "Moraes",
                            Name = "Anthony",
                            PhoneNumber = "(95) 9191-1940"
                        },
                        new
                        {
                            Id = new Guid("8673a8b0-ee19-4a8a-8cd1-c5c938a7121e"),
                            Document = "597.349.216-47",
                            LastName = "Reis",
                            Name = "João",
                            PhoneNumber = "(34) 48249-6560"
                        },
                        new
                        {
                            Id = new Guid("d974c7c0-5fb1-47e1-8b98-e4aed47a4609"),
                            Document = "110.578.706-79",
                            LastName = "Barros",
                            Name = "Maitê",
                            PhoneNumber = "(46) 0674-3029"
                        },
                        new
                        {
                            Id = new Guid("4ac9436d-74a2-41f1-86bb-2d268ff56449"),
                            Document = "640.795.328-35",
                            LastName = "Santos",
                            Name = "Caio",
                            PhoneNumber = "(72) 51134-9251"
                        },
                        new
                        {
                            Id = new Guid("d262d5a0-7b09-419e-98a1-c21d57c52cf1"),
                            Document = "741.013.703-97",
                            LastName = "Oliveira",
                            Name = "Breno",
                            PhoneNumber = "(55) 47766-3617"
                        },
                        new
                        {
                            Id = new Guid("077bedb9-7ba6-4475-a786-241a1833b98e"),
                            Document = "029.398.050-05",
                            LastName = "Santos",
                            Name = "Cauã",
                            PhoneNumber = "(91) 3418-5053"
                        },
                        new
                        {
                            Id = new Guid("fabfea9c-2351-4ce1-aa86-51e7d9a6628f"),
                            Document = "089.142.690-85",
                            LastName = "Melo",
                            Name = "Liz",
                            PhoneNumber = "(89) 49477-6358"
                        },
                        new
                        {
                            Id = new Guid("610ffa71-cc55-43e6-9045-3bf55f3fd998"),
                            Document = "875.881.188-13",
                            LastName = "Reis",
                            Name = "Rafael",
                            PhoneNumber = "+55 (94) 6163-0254"
                        },
                        new
                        {
                            Id = new Guid("2f2b366e-4c70-4233-b6ba-970e5b7bca18"),
                            Document = "702.090.623-60",
                            LastName = "Costa",
                            Name = "Eduardo",
                            PhoneNumber = "+55 (54) 8331-9987"
                        },
                        new
                        {
                            Id = new Guid("c43d3329-fffd-4f1f-a068-c3423058f5e8"),
                            Document = "214.545.217-36",
                            LastName = "Melo",
                            Name = "Heitor",
                            PhoneNumber = "+55 (37) 4247-6872"
                        },
                        new
                        {
                            Id = new Guid("2d56b175-31e6-4795-9768-8acf3c1fbb02"),
                            Document = "144.670.705-44",
                            LastName = "Batista",
                            Name = "Karla",
                            PhoneNumber = "(90) 98958-1067"
                        },
                        new
                        {
                            Id = new Guid("1dcaee80-b7b2-401e-8104-e77326d8a184"),
                            Document = "894.400.156-91",
                            LastName = "Batista",
                            Name = "Calebe",
                            PhoneNumber = "(56) 9621-6254"
                        },
                        new
                        {
                            Id = new Guid("cc61a2c7-7279-4740-b299-7be69d293a14"),
                            Document = "574.495.556-02",
                            LastName = "Carvalho",
                            Name = "Warley",
                            PhoneNumber = "(34) 69662-8044"
                        },
                        new
                        {
                            Id = new Guid("314c9c50-143f-40d8-99aa-fc215c75020e"),
                            Document = "263.804.896-65",
                            LastName = "Franco",
                            Name = "Vitor",
                            PhoneNumber = "(13) 9976-3788"
                        },
                        new
                        {
                            Id = new Guid("7cda5c1f-3e6f-442c-a67d-425c12c41129"),
                            Document = "409.405.113-16",
                            LastName = "Martins",
                            Name = "Aline",
                            PhoneNumber = "(93) 7588-6912"
                        },
                        new
                        {
                            Id = new Guid("82996906-b503-4d5c-b68b-be5d53521195"),
                            Document = "916.330.248-79",
                            LastName = "Saraiva",
                            Name = "Bryan",
                            PhoneNumber = "(98) 33172-2599"
                        },
                        new
                        {
                            Id = new Guid("e917ad6d-0d06-4e79-87aa-3311c47f5513"),
                            Document = "854.805.742-80",
                            LastName = "Costa",
                            Name = "Danilo",
                            PhoneNumber = "(06) 39750-9348"
                        },
                        new
                        {
                            Id = new Guid("cc968289-098b-4909-8d09-c7538bd44509"),
                            Document = "757.412.368-54",
                            LastName = "Franco",
                            Name = "Lorraine",
                            PhoneNumber = "(45) 7090-8886"
                        },
                        new
                        {
                            Id = new Guid("a06869d3-384a-48ee-8f04-cc5e3c1f25ab"),
                            Document = "890.830.226-40",
                            LastName = "Saraiva",
                            Name = "Maria Cecília",
                            PhoneNumber = "(52) 42884-2166"
                        },
                        new
                        {
                            Id = new Guid("be639332-05e1-4012-a914-287e32c63fdb"),
                            Document = "732.249.532-36",
                            LastName = "Moreira",
                            Name = "Ana Laura",
                            PhoneNumber = "+55 (01) 4892-5179"
                        },
                        new
                        {
                            Id = new Guid("9c7c2fe7-b8a5-4e6d-b09b-29db43d2c482"),
                            Document = "616.349.376-16",
                            LastName = "Santos",
                            Name = "Eduardo",
                            PhoneNumber = "(04) 2625-3733"
                        },
                        new
                        {
                            Id = new Guid("801c893a-a993-4713-b614-c375a5194d6a"),
                            Document = "415.313.609-22",
                            LastName = "Braga",
                            Name = "Marcela",
                            PhoneNumber = "(92) 47916-3182"
                        },
                        new
                        {
                            Id = new Guid("169067fd-f917-4628-8b4c-ecba7edb1e47"),
                            Document = "218.798.463-29",
                            LastName = "Franco",
                            Name = "Sarah",
                            PhoneNumber = "(74) 1887-9654"
                        },
                        new
                        {
                            Id = new Guid("f46eb19f-563c-4dca-bf2a-0701338f35b1"),
                            Document = "916.482.450-00",
                            LastName = "Nogueira",
                            Name = "Rafael",
                            PhoneNumber = "(95) 47900-8690"
                        },
                        new
                        {
                            Id = new Guid("584609b7-a06e-49bc-bade-f943854bee0a"),
                            Document = "044.746.003-05",
                            LastName = "Souza",
                            Name = "Noah",
                            PhoneNumber = "(31) 4399-1188"
                        },
                        new
                        {
                            Id = new Guid("a5281a12-090d-46a9-973b-f8cf76327393"),
                            Document = "942.072.184-27",
                            LastName = "Santos",
                            Name = "Emanuelly",
                            PhoneNumber = "+55 (38) 2787-2279"
                        },
                        new
                        {
                            Id = new Guid("f256cabc-721b-43f5-ae44-be20e235da69"),
                            Document = "455.669.102-81",
                            LastName = "Carvalho",
                            Name = "Davi Lucca",
                            PhoneNumber = "+55 (26) 5765-1547"
                        },
                        new
                        {
                            Id = new Guid("74bbd5e5-863c-4fc7-ad84-a965a4235be6"),
                            Document = "451.012.740-34",
                            LastName = "Silva",
                            Name = "Júlio",
                            PhoneNumber = "(27) 8801-1373"
                        },
                        new
                        {
                            Id = new Guid("4762ffbb-2c58-47ad-bc41-965921c86612"),
                            Document = "780.773.119-65",
                            LastName = "Batista",
                            Name = "Lorenzo",
                            PhoneNumber = "+55 (78) 5365-0643"
                        },
                        new
                        {
                            Id = new Guid("e2d10d34-682c-4b9e-8654-2cede9223c6e"),
                            Document = "482.026.906-75",
                            LastName = "Oliveira",
                            Name = "Carla",
                            PhoneNumber = "(40) 92448-9302"
                        });
                });

            modelBuilder.Entity("HospitalBomCodigo.Models.Exam", b =>
                {
                    b.HasOne("HospitalBomCodigo.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
